kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry.kodiradev.de/pdfhero/carbone
    registry: registry.kodiradev.de
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: docker.kodiradev.de
    command_timeout: 2m
    user: root
    key:
      from_secret: deploy_key
    script:
      - ls -lh
      - env


