version: '3'

services:
  carbone:
    build:
      context: .
    restart: unless-stopped
    environment:
      - DEMO=true
      - DEBUG=carbone:*
    volumes:
      - ./templates:/home/node/carbone-api/templates:ro
      - storage:/home/node/carbone-api/storage
    ports:
      - "8080:3030"

volumes:
  storage:
